package io.github.jilipop.ad.swigged.swigtypes;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_RtpCallback {
  private transient long swigCPtr;

  public SWIGTYPE_p_RtpCallback(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_RtpCallback() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_RtpCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

