package io.github.jilipop.ad.swigged;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ortpJNI {
  public static native void ortp_init();
  public static native void ortp_scheduler_init();
  public static native void ortp_exit();
  public static native void ortp_global_stats_display();
  public static native long rtp_session_new(int jarg1);
  public static native void rtp_session_set_scheduling_mode(long jarg1, int jarg2);
  public static native void rtp_session_set_blocking_mode(long jarg1, int jarg2);
  public static native int rtp_session_signal_connect(long jarg1, String jarg2, long jarg3, long jarg4);
  public static native void rtp_session_set_jitter_compensation(long jarg1, int jarg2);
  public static native void rtp_session_enable_adaptive_jitter_compensation(long jarg1, long jarg2);
  public static native void rtp_session_set_time_jump_limit(long jarg1, int jarg2);
  public static native int rtp_session_set_local_addr(long jarg1, String jarg2, int jarg3, int jarg4);
  public static native int rtp_session_set_payload_type(long jarg1, int jarg2);
  public static native void rtp_session_set_connected_mode(long jarg1, long jarg2);
  public static native void rtp_session_enable_rtcp(long jarg1, long jarg2);
  public static native int rtp_session_recv_with_ts(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
  public static native void rtp_session_resync(long jarg1);
  public static native void rtp_session_destroy(long jarg1);
}
