/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <bctoolbox/list.h>

#include <ortp/port.h>
#include <ortp/payloadtype.h>
#include <ortp/rtp.h>
#include <ortp/rtcp.h>
#include <ortp/rtpprofile.h>
#include <ortp/rtpsession.h>
#include <ortp/rtpsignaltable.h>
#include <ortp/event.h>
#include <ortp/logging.h>
#include <ortp/sessionset.h>
#include <ortp/utils.h>
#include <ortp/str_utils.h>
#include <ortp/ortp.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_ortp_1init(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ortp_init();
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_ortp_1scheduler_1init(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ortp_scheduler_init();
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_ortp_1exit(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ortp_exit();
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_ortp_1global_1stats_1display(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ortp_global_stats_display();
}


SWIGEXPORT jlong JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1new(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  RtpSession *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (RtpSession *)rtp_session_new(arg1);
  *(RtpSession **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1scheduling_1mode(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = (int)jarg2; 
  rtp_session_set_scheduling_mode(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1blocking_1mode(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = (int)jarg2; 
  rtp_session_set_blocking_mode(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1signal_1connect(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  RtpSession *arg1 = (RtpSession *) 0 ;
  char *arg2 = (char *) 0 ;
  RtpCallback arg3 ;
  void *arg4 = (void *) 0 ;
  RtpCallback *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(RtpCallback **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null RtpCallback");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(void **)&jarg4; 
  result = (int)rtp_session_signal_connect(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1jitter_1compensation(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = (int)jarg2; 
  rtp_session_set_jitter_compensation(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1enable_1adaptive_1jitter_1compensation(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  bool_t arg2 ;
  bool_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  argp2 = *(bool_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bool_t");
    return ;
  }
  arg2 = *argp2; 
  rtp_session_enable_adaptive_jitter_compensation(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1time_1jump_1limit(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = (int)jarg2; 
  rtp_session_set_time_jump_limit(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1local_1addr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  RtpSession *arg1 = (RtpSession *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)rtp_session_set_local_addr(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1payload_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  RtpSession *arg1 = (RtpSession *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)rtp_session_set_payload_type(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1set_1connected_1mode(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  bool_t arg2 ;
  bool_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  argp2 = *(bool_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bool_t");
    return ;
  }
  arg2 = *argp2; 
  rtp_session_set_connected_mode(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1enable_1rtcp(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  bool_t arg2 ;
  bool_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  argp2 = *(bool_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bool_t");
    return ;
  }
  arg2 = *argp2; 
  rtp_session_enable_rtcp(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1recv_1with_1ts(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  RtpSession *arg1 = (RtpSession *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  int arg3 ;
  uint32_t arg4 ;
  int *arg5 = (int *) 0 ;
  uint32_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(uint32_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(int **)&jarg5; 
  result = (int)rtp_session_recv_with_ts(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1resync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  rtp_session_resync(arg1);
}


SWIGEXPORT void JNICALL Java_io_github_jilipop_ad_swigged_ortpJNI_rtp_1session_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  RtpSession *arg1 = (RtpSession *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(RtpSession **)&jarg1; 
  rtp_session_destroy(arg1);
}


#ifdef __cplusplus
}
#endif

